export const alcoholicDrinks = ["LAŠKO, UNION 0,33L","HEINEKEN 0,33L","HEINEKEN 0.0 0,33L","RADLER 0,5L","VINO 0,1L","ŠPRICER 0,2L","MARTINI BIANCO 0,1L",
  "PENEČE VINO J.P. CHENET 0,2L","KUHANO VINO","VROČI PUNČ","SESTAVINE: RUM, JABOLČNI SOK, MED, LIMONIN SOK, AROMATIČNE ZAČIMBE","VROČI GIN",
  "SESTAVINE: GIN, JABOLČNI SOK, MED, LIMONIN SOK, AROMATIČNE ZAČIMBE"]