export const coctails = ["ESPRESSO MARTINI","SESTAVINE: VODKA, KAVNI LIKER, SVEŽ ESPRESSO, SLADKORNI SIRUP","WHITE RUSSIAN","SESTAVINE: VODKA, KAVNI LIKER, SMETANA",
  "APEROL SPRITZ","SESTAVINE: APEROL, PROSECCO, SODA","GIN TONIK","SESTAVINE: GIN, TONIK, LED, LIMONA","JAGODNI GIN TONIK",
  "SESTAVINE: GIN Z OKUSOM JAGODE, TONIK Z OKUSOM, LED","CUBA LIBRE","SESTAVINE: RUM, COCA COLA, LIMETA, LED","SADEŽI SEJŠELOV",
  "SESTAVINE: KOKOSOV LIKER, ANANASOV SIRUP, TONIK Z OKUSOM - MANGO, LED","SEJŠELSKA MULA","SESTAVINE: RUM, TONIK GINGER BEER, LIMETIN SOK, SODA",
  "HORSE'S NECK","SESTAVINE: VISKI, INGERJEV TONIK, GRENČICA, LED"
]