export const coffee = ["ESPRESSO","DVOJNI ESPRESSO","MACCHIATO","KAVA Z MLEKOM","CAPPUCCINO","MOCHACCINO (KAVA S ČOKOLADO)","KAVA S SMETANO","BELA KAVA",
  "LATTE MACCHIATO","KAVA Z OKUSOM","(VANILIJA, LEŠNIK, KOKOS)","PUMPKIN SPACE LATTE","CORTADO","LEDENA KAVA (ČEZ LED)","LEDENA KAVA Z OKUSOM",
  "(VANILIJA, LEŠNIK, KOKOS)","BABYCCINO","MATCHA LATTE"]