export const spirits = {
  title: "žgane pijače",
  drinks: [
    { name: "kavni liker coffeetissimo 0,03l", price: "3.50 €" },
    { name: "viljamovka 0,03l", price: "4.50 €" },
    { name: "cynar 0,03l", price: "3.50 €" },
    { name: "borovničevec 0,03l", price: "3.50 €" },
    { name: "rum takamaka blank 0,03l", price: "3.00 €" },
    { name: "rum takamaka dark spice 0,03l", price: "3.50 €" },
    { name: "rum ron centenario 20 0,03l", price: "8.00 €" },
    { name: "gin puerto de indias classic 0,03l", price: "3.00 €" },
    { name: "gin puerto de indias strawberry 0,03l", price: "3.00 €" },
    { name: "viski whistler double oak 0,03l", price: "4.00 €" },
    { name: "viski whistler honey 0,03l", price: "3.50 €" },
    { name: "viski jack daniel's 0,03l", price: "3.50 €" },
    { name: "cognac camus vs 0,03l", price: "6.50 €" },
    { name: "tequila sierra 0,03l", price: "3.50 €" },
    { name: "vodka smirnoff 0,03l", price: "3.00 €" },
    { name: "jägermeister 0,03l", price: "3.00 €" },
    { name: "baileys 0,03l", price: "3.00 €" },
  ],
  accessories: [],
};
