const About = () => {
  return (
    <div>
      <h1 className="green">ZAKAJ JE NAŠA KAVA POSEBNA</h1>
      <p className="sup">
        V NAŠI KAVARNI FLOW PRIPRAVLJAMO T.I. "SPECIALTY KAVO"
      </p>
      <p>
        SPECIALTY KAVA PREDSTAVLJA VRHUNSKO KAVO NAJVIJŠE KAKOVOSTI, KI JE
        SKRBNO PRIDELANA NA IZBRANIH PLANTAŽAH IN OCENJENA Z VEČ KOT 80 TOČKAMI
        NA LESTVICI KAKOVOSTI. GRE ZA KAVO Z IZJEMNIM OKUSNIM PROFILOM, KJER SE
        PREPLETAJO NARAVNE AROME, KI SO ZNAČILNE ZA NJEN IZVOR, KOT SO SADNE,
        CVETLIČNE, ČOKOLADNE ALI OREŠČKASTE NOTE. PRI PRIPRAVI SPECIALTY KAVE V
        NAŠI KAVARNI POSVEČAMO POSEBNO POZORNOST SVEŽINI ZRN, PRAVILNEMU MLETJU
        IN TEHNIKAM PRIPRAVE, DA VAM LAHKO PONUDIMO NAJBOLJŠO MOŽNO IZKUŠNJO V
        VSAKI SKODELICI KAVE.
      </p>
    </div>
  );
};

export default About;
